version: '3.8'

services:
  app:
    image: missiondigital
    container_name: missiondigital1
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "gunicorn --bind 0.0.0.0:5000 app:app"
    ports:
      - 5000:5000
    volumes:
      - .:/app
