FROM python:3.11.4-slim-buster

WORKDIR /app

COPY requirements.txt ./

RUN pip install -r requirements.txt

COPY /tests/test_right_payload.py /tests/test_wrong_payload.py /app/

CMD python -m unittest discover /app
